// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Shelter struct {
	ID           int64
	Name         string
	City         string
	State        string
	Country      string
	ZipCode      string
	PhoneNumber  string
	FoundedAt    pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ContactEmail string
}
