// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shelters.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShelter = `-- name: CreateShelter :one
   INSERT INTO shelters (
       name,
       city,
       state,
       country,
       zip_code,
       phone_number,
       contact_email,
       founded_at
   ) VALUES (
       $1,
       $2,
       $3,
       $4,
       $5,
       $6,
       $7,
       $8
   )
   RETURNING
       id,
       name,
       city,
       state,
       country,
       zip_code,
       phone_number,
       contact_email,
       founded_at,
       created_at,
       updated_at
`

type CreateShelterParams struct {
	Name         string
	City         string
	State        string
	Country      string
	ZipCode      string
	PhoneNumber  string
	ContactEmail string
	FoundedAt    pgtype.Date
}

type CreateShelterRow struct {
	ID           int64
	Name         string
	City         string
	State        string
	Country      string
	ZipCode      string
	PhoneNumber  string
	ContactEmail string
	FoundedAt    pgtype.Date
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateShelter(ctx context.Context, arg CreateShelterParams) (CreateShelterRow, error) {
	row := q.db.QueryRow(ctx, createShelter,
		arg.Name,
		arg.City,
		arg.State,
		arg.Country,
		arg.ZipCode,
		arg.PhoneNumber,
		arg.ContactEmail,
		arg.FoundedAt,
	)
	var i CreateShelterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.State,
		&i.Country,
		&i.ZipCode,
		&i.PhoneNumber,
		&i.ContactEmail,
		&i.FoundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
